[project]
name = "stock_analysis_platform_backend"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "amazingdata",
    "apscheduler>=3.11.2",
    "beautifulsoup4>=4.14.3",
    "duckdb>=1.5.2",
    "fastapi[standard]>=0.136.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "openai>=2.37.0",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.0",
    "sqlmodel>=0.0.38",
    "tgw",
    "uvicorn>=0.46.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[tool.uv.sources]
tgw = { path = "backend/deps/tgw-1.0.8.7-py3-none-any.whl" }
amazingdata = { path = "backend/deps/AmazingData-1.1.6-cp312-none-any.whl" }

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.12",
]

[tool.ruff]
line-length = 120
extend-exclude = [
    "backend/tests",
]

[tool.ruff.lint]
extend-select = [
    "E",
    "F",
    "B",
    "SIM",
    "PERF",
    "NPY",
    "PD",
    "FLY",
    "ERA",
    "I",
    "UP",
    "RUF",
    "C4",
    "PT",
]
ignore = [
    "RUF001",
    "RUF002",
    "RUF003",
    "UP006",
    "UP007",
]

[tool.ruff.lint.mccabe]
max-complexity = 10
